const fs = require("fs");

const constants = {
  port: 3000,
  wsPort: process.env.PORT || 8080,
  username: "@" + process.env.TIKTOK_USERNAME,
  sessionId: process.env.SESSION_ID || "",

  test: {
    avatarBuffer: fs.readFileSync("src/assets/avatarBufferTest.png"),
  },

  playerConfig: [
    {
      displayId: "",
      color: "white",
      borderColor: null,
      tier: "base",
      mass: 1,
      size: 0.4,
      health: 10,
      damage: 1,
      diamondCount: 0,
      diamondCountMax: 0,
      avatarUrl: "",
      avatarBuffer: null,
    },
    {
      displayId: "",
      color: "blue",
      borderColor: null,
      tier: "rare",
      mass: 2,
      size: 0.8,
      health: 100,
      damage: 4,
      diamondCount: 1,
      diamondCountMax: 4,
      avatarUrl: "",
      avatarBuffer: null,
    },
    {
      displayId: "",
      color: "purple",
      borderColor: null,
      tier: "mythic",
      mass: 5,
      size: 2,
      health: 400,
      damage: 10,
      diamondCount: 5,
      diamondCountMax: 9,
      avatarUrl: "",
      avatarBuffer: null,
    },
    {
      displayId: "",
      color: "yellow",
      borderColor: null,
      tier: "legendary",
      mass: 12,
      size: 3.5,
      health: 1500,
      damage: 40,
      diamondCount: 10,
      diamondCountMax: 99,
      avatarUrl: "",
      avatarBuffer: null,
    },
    {
      displayId: "",
      color: "red",
      borderColor: null,
      tier: "god",
      mass: 50,
      size: 5.5,
      health: 10000,
      damage: 150,
      diamondCount: 100,
      diamondCountMax: Infinity,
      avatarUrl: "",
      avatarBuffer: null,
    },
  ],
  playerTierKey: ["b", "r", "m", "l", "g"],
};

module.exports = { ...constants };
