const constants = {
  port: 3000,
  wsPort: process.env.PORT || 8080,
  username: process.env.TIKTOK_USERNAME || "@" + "dinhlucsoccer",
  sessionId: process.env.SESSION_ID || "34a5e29039af1d97e7211d9ac2888209",

  playerConfig: [
    {
      displayId: "",
      color: "white",
      borderColor: null,
      tier: "base",
      mass: 1,
      size: 0.4,
      health: 10,
      damage: 1,
      diamondCount: 0,
      attended: null,
      avatarUrl: "",
      avatarBuffer: "",
    },
    {
      displayId: "",
      color: "blue",
      borderColor: null,
      tier: "rare",
      mass: 3,
      size: 1,
      health: 100,
      damage: 4,
      diamondCount: 1,
      attended: null,
      avatarUrl: "",
      avatarBuffer: "",
    },
    {
      displayId: "",
      color: "purple",
      borderColor: null,
      tier: "mythic",
      mass: 8,
      size: 2,
      health: 400,
      damage: 10,
      diamondCount: 5,
      attended: null,
      avatarUrl: "",
      avatarBuffer: "",
    },
    {
      displayId: "",
      color: "yellow",
      borderColor: null,
      tier: "legendary",
      mass: 25,
      size: 3.5,
      health: 1500,
      damage: 40,
      diamondCount: 10,
      attended: null,
      avatarUrl: "",
      avatarBuffer: "",
    },
    {
      displayId: "",
      color: "red",
      borderColor: null,
      tier: "god",
      mass: 100,
      size: 6,
      health: 10000,
      damage: 150,
      diamondCount: 100,
      attended: null,
      avatarUrl: "",
      avatarBuffer: "",
    },
  ],
};

module.exports = { ...constants };
