const constants = {
  port: 3000,
  wsPort: process.env.PORT || 8080,
  username: "@ductoan.muc",

  playerConfig: [
    {
      displayId: "",
      color: "white",
      borderColor: null,
      tier: "base",
      mass: 1,
      size: 0.4,
      health: 10,
      damage: 1,
      diamondCount: 0,
      attended: null,
      avatarUrl: "",
      avatarBuffer: "",
      isWelcome: false,
      message: "",
    },
    {
      displayId: "",
      color: "blue",
      borderColor: null,
      tier: "rare",
      mass: 2,
      size: 1,
      health: 200,
      damage: 3,
      diamondCount: 1,
      attended: null,
      avatarUrl: "",
      avatarBuffer: "",
      isWelcome: false,
      message: "",
    },
    {
      displayId: "",
      color: "purple",
      borderColor: null,
      tier: "mythic",
      mass: 5,
      size: 2,
      health: 500,
      damage: 10,
      diamondCount: 5,
      attended: null,
      avatarUrl: "",
      avatarBuffer: "",
      isWelcome: false,
      message: "",
    },
    {
      displayId: "",
      color: "yellow",
      borderColor: null,
      tier: "legendary",
      mass: 20,
      size: 3.5,
      health: 2000,
      damage: 40,
      diamondCount: 10,
      attended: null,
      avatarUrl: "",
      avatarBuffer: "",
      isWelcome: false,
      message: "",
    },
    {
      displayId: "",
      color: "red",
      borderColor: null,
      tier: "god",
      mass: 100,
      size: 6,
      health: 10000,
      damage: 100,
      diamondCount: 200,
      attended: null,
      avatarUrl: "",
      avatarBuffer: "",
      isWelcome: false,
      message: "",
    },
  ],
};

module.exports = { ...constants };
